name: CI

on:
  push:
  pull_request:
    branches:
      - 'main'

env:
  SRC_DIR: scrapers
  TEST_DIR: test

jobs:
  style_lint_and_type_check:
    name: style lint and type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip3 install --upgrade pip
          pip3 install flake8 mypy black types-PyYAML
      - run: |
          python3 -m black --check $TEST_DIR
          python3 -m flake8 $TEST_DIR # should also run against scrapers but that will need more cleanup
          python3 -m mypy $TEST_DIR --follow-imports=skip --disallow-untyped-defs
